### PR TITLE
Remove use of existential types and Scapegoat types in typeOf

### LINKED ISSUE #222: Maven integration requires scalac-scapegoat-plugin as a dependency
We don't want to include scalac-scapegoat-plugin as a dependency of our product due to the following reasons:
* scalac-scapegoat-plugin comes to the product package but is not acutally used by the product
   * to avoid this issue, we have to put special inclusions in the assembly descriptor
* we have checks for unused dependencies by maven-dependency-plugin and these checks fail due to scalac-scapegoat-plugin
   * to avoid this issue, we have to put a special exclusion to the configuration of maven-dependency-plugin

I tried to include scalac-scapegoat-plugin as a **dependency of scala-maven-plugin** rather than of the product itself, but this does not work:
```
[ERROR] error: scala.ScalaReflectionException: object com.sksamuel.scapegoat.Safe in compiler mirror not found.
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:129)
[ERROR]         at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:29)
...
```

### PR DESCRIPTION
**Pull request by joshrosen-stripe**
This PR removes all uses of existential types and Scapegoat types in `typeOf[]`. If Scapegoat classes are not on the compile classpath then these `typeOf`s caused `scala.ScalaReflectionException: object <type> in compiler mirror not found` exceptions during compilation (see #222, #167, #163, #98).

To do this, I added several `is<type>(tree: Tree)` helper methods to the `InspectionContext.Traverser` trait. There's a couple of details which I'll discuss in PR self-review comments.

I tested this by integrating Scapegoat into a Bazel build.

Fixes #222.

### CODE REVIEW

File: src/main/scala/com/sksamuel/scapegoat/Inspection.scala [hunk 1]
```diff
@@ -94,6 +97,18 @@ case class InspectionContext(global: Global, feedback: Feedback) {
         case _ => inspect(tree)
       }
     }
+
+    protected def isArray(tree: Tree): Boolean = tree.tpe.typeSymbol.fullName == "scala.Array"
+    protected def isTraversable(tree: Tree): Boolean = tree.tpe <:< typeOf[Traversable[Any]]
+    protected def isSeq(t: Tree): Boolean = t.tpe <:< typeOf[Seq[Any]]
```
Comment (joshrosen-stripe) [inline src/main/scala/com/sksamuel/scapegoat/Inspection.scala]: The `Seq` and `IndexedSeq` methods here are based on the change in #163

File: src/main/scala/com/sksamuel/scapegoat/Inspection.scala [hunk 2]
```diff
@@ -94,6 +97,18 @@ case class InspectionContext(global: Global, feedback: Feedback) {
         case _ => inspect(tree)
       }
     }
+
+    protected def isArray(tree: Tree): Boolean = tree.tpe.typeSymbol.fullName == "scala.Array"
+    protected def isTraversable(tree: Tree): Boolean = tree.tpe <:< typeOf[Traversable[Any]]
```
Comment (joshrosen-stripe) [inline src/main/scala/com/sksamuel/scapegoat/Inspection.scala]: This is based on the `Traversable` fix from #167

File: src/main/scala/com/sksamuel/scapegoat/Inspection.scala [hunk 3]
```diff
@@ -94,6 +97,18 @@ case class InspectionContext(global: Global, feedback: Feedback) {
         case _ => inspect(tree)
       }
     }
+
+    protected def isArray(tree: Tree): Boolean = tree.tpe.typeSymbol.fullName == "scala.Array"
```
Comment (joshrosen-stripe) [inline src/main/scala/com/sksamuel/scapegoat/Inspection.scala]: Similar fix from WartRemover: https://github.com/wartremover/wartremover/commit/cecf0d13017063713e548b05e11b1ae69395123c

File: src/main/scala/com/sksamuel/scapegoat/Inspection.scala [hunk 4]
```diff
@@ -94,6 +97,18 @@ case class InspectionContext(global: Global, feedback: Feedback) {
...
+    protected def isTraversable(tree: Tree): Boolean = tree.tpe <:< typeOf[Traversable[Any]]
+    protected def isSeq(t: Tree): Boolean = t.tpe <:< typeOf[Seq[Any]]
+    protected def isIndexedSeq(t: Tree): Boolean = t.tpe <:< typeOf[IndexedSeq[Any]]
+    protected def isSet(t: Tree): Boolean = {
+      t.tpe.widen.baseClasses.exists { c =>
+        c.fullName == "scala.collection.mutable.Set" || c.fullName == "scala.collection.immutable.Set"
+      }
+    }
+    protected def isList(t: Tree): Boolean = t.tpe <:< typeOf[scala.collection.immutable.List[Any]]
```
Comment (joshrosen-stripe) [inline src/main/scala/com/sksamuel/scapegoat/Inspection.scala]: List is covariant, which I think is why we're able to use `Any` here, similar to the solution for `Traversable` and `Seq` / `IndexedSeq` (which are also covariant).

File: src/main/scala/com/sksamuel/scapegoat/Inspection.scala [hunk 5]
```diff
@@ -94,6 +97,18 @@ case class InspectionContext(global: Global, feedback: Feedback) {
...
+    protected def isMap(tree: Tree): Boolean = tree.tpe.baseClasses.exists { _.fullName == "scala.collection.Map" }
```
Comment (joshrosen-stripe) [inline src/main/scala/com/sksamuel/scapegoat/Inspection.scala]: `scala.collection.Map` is invariant in its key type, which is why we can't do `Map[Any, Any]` here.

File: src/main/scala/com/sksamuel/scapegoat/Inspection.scala [hunk 6]
```diff
@@ -94,6 +97,18 @@ case class InspectionContext(global: Global, feedback: Feedback) {
         case _ => inspect(tree)
       }
     }
+
+    protected def isArray(tree: Tree): Boolean = tree.tpe.typeSymbol.fullName == "scala.Array"
+    protected def isTraversable(tree: Tree): Boolean = tree.tpe <:< typeOf[Traversable[Any]]
+    protected def isSeq(t: Tree): Boolean = t.tpe <:< typeOf[Seq[Any]]
+    protected def isIndexedSeq(t: Tree): Boolean = t.tpe <:< typeOf[IndexedSeq[Any]]
+    protected def isSet(t: Tree): Boolean = {
```
Comment (joshrosen-stripe) [inline src/main/scala/com/sksamuel/scapegoat/Inspection.scala]: Similar to the `Map` case discussed below, I think we need to do this method of searching base classes instead of `Set[Any]` because set is invariant in its type parameter.

**Comment by joshrosen-stripe** [comment]
Hi @sksamuel, do you have time to review this PR which fixes ScalaReflectionExceptions when Scapegoat classes are only on the plugin classpath and not the compile classpath? This should fix a longstanding set of pain points when using Scapegoat with non-SBT build tools (including Maven, Bazel, etc.).

I'm pinging as part of a review of all of my open PRs, trying to figure out which can be unblocked  and merged (or abandoned and closed).

**Comment by sksamuel** [comment]
merged, thanks !

**Comment by joshrosen-stripe** [comment]
Thanks for the merge and new release! 💯
